<?php
/**
 * PricingSummary
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  ld\php\sdkEbayInventory
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ld\php\sdkEbayInventory\Model;

use \ArrayAccess;
use \ld\php\sdkEbayInventory\ObjectSerializer;

/**
 * PricingSummary Class Doc Comment
 *
 * @category Class
 * @description This type is used to specify the listing price for the product and settings for the Minimum Advertised Price and Strikethrough Pricing features. The &lt;strong&gt;price&lt;/strong&gt; field must be supplied before an offer is published, but a seller may create an offer without supplying a price initially. The Minimum Advertised Price feature is only available on the US site. Strikethrough Pricing is available on the US, eBay Motors, UK, Germany, Canada (English and French), France, Italy, and Spain sites.
 * @package  ld\php\sdkEbayInventory
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class PricingSummary implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PricingSummary';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'auctionReservePrice' => '\ld\php\sdkEbayInventory\Model\Amount',
        'auctionStartPrice' => '\ld\php\sdkEbayInventory\Model\Amount',
        'minimumAdvertisedPrice' => '\ld\php\sdkEbayInventory\Model\Amount',
        'originallySoldForRetailPriceOn' => 'string',
        'originalRetailPrice' => '\ld\php\sdkEbayInventory\Model\Amount',
        'price' => '\ld\php\sdkEbayInventory\Model\Amount',
        'pricingVisibility' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'auctionReservePrice' => null,
        'auctionStartPrice' => null,
        'minimumAdvertisedPrice' => null,
        'originallySoldForRetailPriceOn' => null,
        'originalRetailPrice' => null,
        'price' => null,
        'pricingVisibility' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'auctionReservePrice' => 'auctionReservePrice',
        'auctionStartPrice' => 'auctionStartPrice',
        'minimumAdvertisedPrice' => 'minimumAdvertisedPrice',
        'originallySoldForRetailPriceOn' => 'originallySoldForRetailPriceOn',
        'originalRetailPrice' => 'originalRetailPrice',
        'price' => 'price',
        'pricingVisibility' => 'pricingVisibility'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'auctionReservePrice' => 'setAuctionReservePrice',
        'auctionStartPrice' => 'setAuctionStartPrice',
        'minimumAdvertisedPrice' => 'setMinimumAdvertisedPrice',
        'originallySoldForRetailPriceOn' => 'setOriginallySoldForRetailPriceOn',
        'originalRetailPrice' => 'setOriginalRetailPrice',
        'price' => 'setPrice',
        'pricingVisibility' => 'setPricingVisibility'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'auctionReservePrice' => 'getAuctionReservePrice',
        'auctionStartPrice' => 'getAuctionStartPrice',
        'minimumAdvertisedPrice' => 'getMinimumAdvertisedPrice',
        'originallySoldForRetailPriceOn' => 'getOriginallySoldForRetailPriceOn',
        'originalRetailPrice' => 'getOriginalRetailPrice',
        'price' => 'getPrice',
        'pricingVisibility' => 'getPricingVisibility'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['auctionReservePrice'] = $data['auctionReservePrice'] ?? null;
        $this->container['auctionStartPrice'] = $data['auctionStartPrice'] ?? null;
        $this->container['minimumAdvertisedPrice'] = $data['minimumAdvertisedPrice'] ?? null;
        $this->container['originallySoldForRetailPriceOn'] = $data['originallySoldForRetailPriceOn'] ?? null;
        $this->container['originalRetailPrice'] = $data['originalRetailPrice'] ?? null;
        $this->container['price'] = $data['price'] ?? null;
        $this->container['pricingVisibility'] = $data['pricingVisibility'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets auctionReservePrice
     *
     * @return \ld\php\sdkEbayInventory\Model\Amount|null
     */
    public function getAuctionReservePrice()
    {
        return $this->container['auctionReservePrice'];
    }

    /**
     * Sets auctionReservePrice
     *
     * @param \ld\php\sdkEbayInventory\Model\Amount|null $auctionReservePrice auctionReservePrice
     *
     * @return self
     */
    public function setAuctionReservePrice($auctionReservePrice)
    {
        $this->container['auctionReservePrice'] = $auctionReservePrice;

        return $this;
    }

    /**
     * Gets auctionStartPrice
     *
     * @return \ld\php\sdkEbayInventory\Model\Amount|null
     */
    public function getAuctionStartPrice()
    {
        return $this->container['auctionStartPrice'];
    }

    /**
     * Sets auctionStartPrice
     *
     * @param \ld\php\sdkEbayInventory\Model\Amount|null $auctionStartPrice auctionStartPrice
     *
     * @return self
     */
    public function setAuctionStartPrice($auctionStartPrice)
    {
        $this->container['auctionStartPrice'] = $auctionStartPrice;

        return $this;
    }

    /**
     * Gets minimumAdvertisedPrice
     *
     * @return \ld\php\sdkEbayInventory\Model\Amount|null
     */
    public function getMinimumAdvertisedPrice()
    {
        return $this->container['minimumAdvertisedPrice'];
    }

    /**
     * Sets minimumAdvertisedPrice
     *
     * @param \ld\php\sdkEbayInventory\Model\Amount|null $minimumAdvertisedPrice minimumAdvertisedPrice
     *
     * @return self
     */
    public function setMinimumAdvertisedPrice($minimumAdvertisedPrice)
    {
        $this->container['minimumAdvertisedPrice'] = $minimumAdvertisedPrice;

        return $this;
    }

    /**
     * Gets originallySoldForRetailPriceOn
     *
     * @return string|null
     */
    public function getOriginallySoldForRetailPriceOn()
    {
        return $this->container['originallySoldForRetailPriceOn'];
    }

    /**
     * Sets originallySoldForRetailPriceOn
     *
     * @param string|null $originallySoldForRetailPriceOn This field is needed if the Strikethrough Pricing (STP) feature will be used in the offer. This field indicates that the product was sold for the price in the <strong>originalRetailPrice</strong> field on an eBay site, or sold for that price by a third-party retailer. When using the <strong>createOffer</strong> or <strong>updateOffer</strong> calls, the seller will pass in a value of <code>ON_EBAY</code> to indicate that the product was sold for the <strong>originalRetailPrice</strong> on an eBay site, or the seller will pass in a value of <code>OFF_EBAY</code> to indicate that the product was sold for the <strong>originalRetailPrice</strong> through a third-party retailer. This field and the <strong>originalRetailPrice</strong> field are only applicable if the seller and listing are eligible to use the Strikethrough Pricing feature, a feature which is limited to the US (core site and Motors), UK, Germany, Canada (English and French versions), France, Italy, and Spain sites.<br/><br/>This field will be returned if set for the offer. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/inventory/types/slr:SoldOnEnum'>eBay API documentation</a>
     *
     * @return self
     */
    public function setOriginallySoldForRetailPriceOn($originallySoldForRetailPriceOn)
    {
        $this->container['originallySoldForRetailPriceOn'] = $originallySoldForRetailPriceOn;

        return $this;
    }

    /**
     * Gets originalRetailPrice
     *
     * @return \ld\php\sdkEbayInventory\Model\Amount|null
     */
    public function getOriginalRetailPrice()
    {
        return $this->container['originalRetailPrice'];
    }

    /**
     * Sets originalRetailPrice
     *
     * @param \ld\php\sdkEbayInventory\Model\Amount|null $originalRetailPrice originalRetailPrice
     *
     * @return self
     */
    public function setOriginalRetailPrice($originalRetailPrice)
    {
        $this->container['originalRetailPrice'] = $originalRetailPrice;

        return $this;
    }

    /**
     * Gets price
     *
     * @return \ld\php\sdkEbayInventory\Model\Amount|null
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param \ld\php\sdkEbayInventory\Model\Amount|null $price price
     *
     * @return self
     */
    public function setPrice($price)
    {
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets pricingVisibility
     *
     * @return string|null
     */
    public function getPricingVisibility()
    {
        return $this->container['pricingVisibility'];
    }

    /**
     * Sets pricingVisibility
     *
     * @param string|null $pricingVisibility This field is needed if the Minimum Advertised Price (MAP) feature will be used in the offer. This field is only applicable if an eligible US seller is using the Minimum Advertised Price (MAP) feature and a <strong>minimumAdvertisedPrice</strong> has been specified. The value set in this field will determine whether the MAP price is shown to a prospective buyer prior to checkout through a pop-up window accessed from the View Item page, or if the MAP price is not shown until the checkout flow after the buyer has already committed to buying the item. To show the MAP price prior to checkout, the seller will set this value to <code>PRE_CHECKOUT</code>. To show the MAP price after the buyer already commits to buy the item, the seller will set this value to <code>DURING_CHECKOUT</code>. This field will be ignored if the seller and/or the listing is not eligible for the MAP feature.<br/><br/>This field will be returned if set for the offer. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/inventory/types/slr:MinimumAdvertisedPriceHandlingEnum'>eBay API documentation</a>
     *
     * @return self
     */
    public function setPricingVisibility($pricingVisibility)
    {
        $this->container['pricingVisibility'] = $pricingVisibility;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


